# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68450bdc89dd90230a2f203f16a393b11d1250437c2798b24aa72a8fabd8ac5340fd9b2593a471a62e1a434febb6acad2bd72e4832dd64e9230972c75ea299c7

test:
  secret_key_base: 17dcb17e99b41d3847d56cfb657aa2b050920a890da538b9bc8ee3e5d9999a5a1d43365bad9f0643018a17b6a4cb410dfaa7140a3a0c65204709fba60ded60f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
